"""empty message

Revision ID: 40254d63cd21
Revises: a5aa8d785f67
Create Date: 2022-10-25 00:11:43.716642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40254d63cd21'
down_revision = 'a5aa8d785f67'
branch_labels = None
depends_on = None


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    # ### end Alembic commands ###


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('html', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
